# Generated by Django 3.1 on 2020-08-30 16:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('display_picture', models.ImageField(blank=True, default='https://placehold.it/30x30', upload_to='users/%Y/%m/%d/')),
                ('bio', models.CharField(blank=True, max_length=140, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
