# Generated by Django 3.1 on 2020-08-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(blank=True, default='default_avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
