# Generated by Django 3.1 on 2020-08-19 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KwikPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('featured_image', models.ImageField(upload_to='user_posts/images/%Y/%m/%d/')),
                ('post_body', models.TextField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post_likes', models.ManyToManyField(blank=True, related_name='kwiktalk_posts_liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwikposts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
