# Generated by Django 3.1 on 2020-08-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwikpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
