# Generated by Django 3.1 on 2020-08-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikposts', '0002_kwikpost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwikpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
