# Generated by Django 3.1 on 2020-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwikposts', '0003_auto_20200822_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kwikpost',
            options={'ordering': ('-created_at',)},
        ),
    ]
